AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CDSSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: cdss-prod-cluster
      Version: '1.26'
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds: !Ref Subnets

  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: CDSS Cluster Security Group
      VpcId: !Ref VpcId