apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cdss-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cdss-backend
  endpoints:
  - port: web
    interval: 30s
    path: /metrics